toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link
  - code
  - autoresize
  - emoticons
  - fullpage
  - media
  - wordcount
  - autosave
  - preview
  - paste


